UTEN-214 - replace babel-eslint with @babel/eslint-parser
folio-org/ui-tenant-settings pull request #328
Opened 2023-01-05 11:04 UTC by Terala-Priyanka

## Purpose
replace babel-eslint with @babel/eslint-parser
Issue: https://issues.folio.org/browse/UITEN-214

## Approach
1. replaced babel-eslint dev dependency with @babel/eslint-parser
2. added new eslint libraries eslint-import-resolver-alias eslint-import-resolver-webpack @babel/core eslint@^7.32.0 @folio/eslint-config-stripes@^6.1.0
3. updated .eslintrc file to pick @babel/eslint-parser as parser
4. fixed few lint issues

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-01-05 12:05 UTC, zburke approved these changes
LGTM. There are several additional lint errors that it would be great to clean up, mostly related to props validation and missing `useEffect` dependencies.

2023-01-06 10:26 UTC, Terala-Priyanka commented
> LGTM. There are several additional lint errors that it would be great to clean up, mostly related to props validation and missing `useEffect` dependencies.

@zburke I agree there are more lint errors. I will have to sneak into the associated pages and scenarios in order to cleanly fix them. I would be happy to pick up a new ticket for those changes.

2023-01-06 12:59 UTC, Dmitriy-Litvinenko requested changes

2023-01-06 13:11 UTC, Dmitriy-Litvinenko commented on package.json
> +    "@folio/eslint-config-stripes": "^6.3.10000070",
@zburke Thank you
@Terala-Priyanka Could you please change to "v6.3.1"?

2023-01-06 14:21 UTC, Dmitriy-Litvinenko approved these changes

2023-01-06 18:48 UTC, zburke approved these changes

2023-01-09 05:29 UTC, merged